queue_rules:
  - name: default
    queue_conditions:
      - base=main
      - label~=merge-queue|dependencies
    merge_conditions:
    - check-success=buildbot/nix-build
    batch_size: 5
    merge_method: rebase
pull_request_rules:
  - name: merge using the merge queue
    conditions:
    actions:
      queue: {}
